# Generated by Django 5.1.2 on 2025-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('bullets', models.TextField(help_text='Separate each item with a semicolon (;)')),
                ('brochure_1', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('brochure_2', models.FileField(blank=True, null=True, upload_to='brochures/')),
            ],
        ),
    ]
